name: Update README Stats on Push

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    # ESTA PARTE É A MAIS IMPORTANTE
    # "permissions:" deve estar alinhado com "runs-on:"
    # "contents:" deve ter dois espaços de recuo
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # O resto do arquivo...
      - name: Update README with new timestamp
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s/__TIMESTAMP__/${TIMESTAMP}/g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: auto-update README stats"
          git push
